server:
  port: 8083

spring:
  application:
    name: api-gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

cloud:
  gateway:
    routes:
      - id: USER-SERVICE
         uri: lb://USER-SERVICE
         predicates:
           - Path=/user/**

       - id: POST-SERVICE
         uri: lb://DEPARTMENT-SERVICE
         predicates:
           - Path=/post/**
        filters:

